---
- name: Setup Flask App on EC2
  hosts: ec2_instance
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask

    - name: Clone the Git repository
      git:
        repo: "https://github.com/aonyshc/rqg-py.git"
        dest: "/home/ubuntu/random_quote_generator"
        version: master

    - name: Create a systemd service file for Flask app
      copy:
        dest: /etc/systemd/system/flask_app.service
        content: |
          [Unit]
          Description=Flask Application
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/random_quote_generator
          ExecStart=/usr/bin/python3 /home/ubuntu/random_quote_generator/app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target
      become: yes

    - name: Reload systemd daemon
      command: systemctl daemon-reload
      become: yes

    - name: Enable and start Flask app service
      systemd:
        name: flask_app
        enabled: yes
        state: started
      become: yes

